version: '3'
services:
  wep_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: